### ISSUE TITLE
Fringe error catch

### ISSUE THREAD

**Issue by nolochemical** [danielb2/blipp#11]
Hapijs 8.x

Have not confirmed if this is a hapijs feature or bug just thought its was worth note.

// here # 2 will be used, #1 ignored.
server.route({
  config: { description: "descrip 1" },
  config: { description: "descrip 2" }
});

**Comment by danielb2** [comment]
It's an artifact of javascript, not of hapi nor blipp.

``` bash
$ node
> var object = {
... config: 1,
... config: 2
... };
undefined
> object
{ config: 2 }
```

**Comment by nolochemical** [comment]
Ahh, thanks good to know =)
