### ISSUE TITLE
showAuth option doesn't work for 'required' or 'optional' auth strategies

### ISSUE THREAD

**Issue by bryanbecker** [danielb2/blipp#18]
showAuth only displays authorization strategies correctly if they are specifically noted in the routes.

**Comment by danielb2** [comment]
Do you have an example of a setup where it's not working?

**Comment by bryanbecker** [comment]
server config:
`server.auth.default(my_default_auth_strategy);`

routing:
```
{ path: '/users/',
  method: 'GET',
  // no auth strategy specified
  handler: user_handler
}
```

Blipp output:
`GET    /users                         none`

**Comment by dave-irvine** [comment]
+1 just ran into this issue

**Comment by danielb2** [comment]
I'll have a look soon

**Comment by dave-irvine** [comment]
So you can pull the default scheme from `server.connections[0].auth.settings.default`. Obviously you don't want to hard reference the first connection, so I managed to get as far as this:


```
routingTable.forEach(function (connection) {
                var defaultAuthScheme;
                server.connections.forEach(function (serverConnection) {
                        if (serverConnection.info.id === connection.info.id) {
                                defaultAuthScheme = serverConnection.auth.settings.default;              
                        }
                });
            var title = Chalk.underline(connection.info.uri);
```

but as a scheme can have a variable number of strategies I can't figure a reliable way to get the default one.

**Comment by danielb2** [comment]
Thanks, I'll take a PR of course too.

**Comment by dave-irvine** [comment]
If I had a complete fix I would do a PR but I can't figure out getting the default strategy name.

**Comment by danielb2** [comment]
Alright, I have a fix in this branch: https://github.com/danielb2/blipp/tree/fix.showauth

I have some house cleaning to do but please check to see if it's doing what you expect.

I had to make the assumption that the default strategy array will only ever have one value (how can you have more than one default?)

**Comment by danielb2** [comment]
Oh, and @dave-irvine   your findings were very helpful. Thank you

**Comment by danielb2** [comment]
I removed the assumption that it's an array in the latest commit. So never mind that part

**Comment by dave-irvine** [comment]
Can't test this until Tuesday, but commits look good, thanks for the work!
