### ISSUE TITLE
Add custom properties to table

### ISSUE THREAD

**Issue by woutrbe** [danielb2/blipp#24]
This might be outside this project's scope, but I'm wondering if there's any way to add custom properties to the table?

For example; in the below route, I make use of different plugins for access permissions, ideally I would like to display these permissions during startup in the table.

`{
    method: 'POST',
    path: '/api/example',
    config: {
        description: 'Example route',
        auth: 'bearer',
        plugins: {
            access: {
                mustInclude: ['primary']
            },
            validate: {
                headers: Joi.object().options({ allowUnknown: true })
            }
        },
        handler: function() { }
}`

**Comment by danielb2** [comment]
How would you organize the display of this? there's a limited amount of screen real-estate

**Comment by woutrbe** [comment]
Good question, I didn't really think about that yet. I guess one of the options could be a customisable display that allows you to display up to 5 properties. 
I'm not sure if this would be a good solution. Or if this should even be added to this project. (As I've only encountered this problem once)

**Comment by danielb2** [comment]
I'll close for now. If it comes up again I'll reconsider. thanks :)
