### ISSUE TITLE
Add demo/example

### ISSUE THREAD

**Issue by Y-LyN-10** [danielb2/blipp#35]
Yes, using blipp is really easy and straightforward, but I think that it would be great to have a simple demo that runs via `$ npm run demo` :) 

This would help new contributors to test/explore the project without monkey-patching the dependency on their existing projects. Also, it is a good first issue for such new contributors.

**Comment by danielb2** [comment]
That's a great idea. To check it yesterday I copied and pasted the example in the readme, and it would have been much easier to just have an example.
